# Generated by Django 5.1.4 on 2025-02-26 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.CharField(max_length=1)),
                ('url', models.URLField()),
                ('related_encuestas', models.ManyToManyField(blank=True, to='datamerge.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('comunidad_autonoma', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('pri_sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_colegios', to='datamerge.encuesta')),
                ('pro_sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_colegios', to='datamerge.encuesta')),
                ('sec_sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_colegios', to='datamerge.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('encuestas_cubiertas', models.IntegerField()),
                ('encuestas_incompletas', models.IntegerField()),
                ('encuestas_totales', models.IntegerField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='datamerge.encuesta')),
            ],
            options={
                'unique_together': {('encuesta', 'date')},
            },
        ),
    ]
