# Generated by Django 5.1.4 on 2025-02-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datamerge", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="encuesta",
            old_name="titulo_encuesta",
            new_name="titulo",
        ),
    ]
