# Generated by Django 5.1.4 on 2025-02-04 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamerge', '0002_rename_titulo_encuesta_encuesta_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('comunidad_autonoma', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='related_encuestas',
            field=models.ManyToManyField(blank=True, to='datamerge.encuesta'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='colegio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='datamerge.colegio'),
        ),
    ]
