# Generated by Django 5.1.4 on 2025-02-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamerge', '0003_colegio_encuesta_related_encuestas_encuesta_colegio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='colegio',
        ),
        migrations.AddField(
            model_name='colegio',
            name='pri_sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_colegios', to='datamerge.encuesta'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='pro_sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_colegios', to='datamerge.encuesta'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='sec_sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_colegios', to='datamerge.encuesta'),
        ),
    ]
