# Generated by Django 5.1.4 on 2025-02-25 08:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamerge', '0004_remove_encuesta_colegio_colegio_pri_sid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='encuestas_cubiertas',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='encuestas_incompletas',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='encuestas_totales',
        ),
        migrations.CreateModel(
            name='EncuestaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('encuestas_cubiertas', models.IntegerField()),
                ('encuestas_incompletas', models.IntegerField()),
                ('encuestas_totales', models.IntegerField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='datamerge.encuesta')),
            ],
            options={
                'unique_together': {('encuesta', 'date')},
            },
        ),
    ]
