# Generated by Django 5.1.4 on 2025-02-25 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamerge', '0005_remove_encuesta_encuestas_cubiertas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestaresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
